### PR TITLE
Updating Kub-recommended resources

### PR DESCRIPTION
**Pull request by Hemal1P**
Modifying the Kubernetes recommended resources for different types of deployments.

### CODE REVIEW

**Comment by chasdl** [comment]
Thanks Hemal! I'm thinking we can modify the table values. `2000` is a bit low for the high volume deployment, let's adjust the range a bit to `5000`. Let's do:

| 100 - 5000  |  High Volume Deployment  |
| 5000+  |  Very High Volume Deployment  |

**Review by black-bryan — COMMENTED** [review]
In [line 181](https://github.com/1Password/scim-examples/blob/e66b8d9b014ba11af3ec3c331ea34828065252e8/kubernetes/README.md?plain=1#L181), we call out **high volume deployments where there is a large number of users and/or groups.** This seems like it should be 1000-5000 for high volume and default being 1-1000 users? Above 100 users does not seem like a large number of users for most accounts.

**Comment by chasdl** [comment]
@ag-adampike Has brought up some research on K8's resource management that we should take the time to explore:

[CPU requests should be defined, but limits should not](https://home.robusta.dev/blog/stop-using-cpu-limits) (to allow for efficient use of available CPU)
[Memory limits should be set to the same value as requests](https://home.robusta.dev/blog/kubernetes-memory-limit) (to avoid OOM kills)

For some historical context, we have been configuring both `requests` and `limits` per Kubernetes documentation ([on CPU](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#if-you-do-not-specify-a-cpu-limit), on [Memory](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#if-you-do-not-specify-a-memory-limit)). The reasons outlined above for not setting limits on CPU and setting the limit == request make sense, but we need to do more research if it fits our particular use-case.

**Comment by chasdl** [comment]
@Hemal1P Any luck verifying your commits? You should be able to upload your public key.

**Comment by Hemal1P** [comment]
Hey @chasdl Thank you !  it worked 🙌

**Review by chasdl — APPROVED** [review]

**Pull request merged**
